language: node_js
node_js:
  - "v10.15.3"

cache: npm

before_script:
  - pwd
  - ls -al
  - cd ./pendulum && npm install

script:
  - cd ./pendulum && npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master